//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASKET
    {
        public int basket_id { get; set; }
        public int product_id { get; set; }
        public int users_id { get; set; }
        public int quantity { get; set; }
    
        public virtual PRODUCTS PRODUCTS { get; set; }
        public virtual PRODUCTS PRODUCTS1 { get; set; }
        public virtual USERS USERS { get; set; }
        public virtual USERS USERS1 { get; set; }
    }
}
