//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS()
        {
            this.BASKET = new HashSet<BASKET>();
            this.BASKET1 = new HashSet<BASKET>();
            this.PURCHASE = new HashSet<PURCHASE>();
            this.PURCHASE1 = new HashSet<PURCHASE>();
        }
    
        public int product_id { get; set; }
        public int category_id { get; set; }
        public int type_id { get; set; }
        public int firm_id { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string description { get; set; }
        public string image { get; set; }

        public string CurrentPhoto
        {
            get
            {
                if (String.IsNullOrEmpty(image) || String.IsNullOrWhiteSpace(image))
                {
                    return "/Images/picture.jpg";
                }
                else
                {
                    return "/Images/" + image;
                }
            }
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASKET> BASKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASKET> BASKET1 { get; set; }
        public virtual CATEGORIES CATEGORIES { get; set; }
        public virtual CATEGORIES CATEGORIES1 { get; set; }
        public virtual FIRM FIRM { get; set; }
        public virtual FIRM FIRM1 { get; set; }
        public virtual TYPE TYPE { get; set; }
        public virtual TYPE TYPE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE> PURCHASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE> PURCHASE1 { get; set; }
    }
}
