//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASE
    {
        public int purchase_id { get; set; }
        public int zakaz_id { get; set; }
        public int product_id { get; set; }
        public int quantity { get; set; }
    
        public virtual PRODUCTS PRODUCTS { get; set; }
        public virtual PRODUCTS PRODUCTS1 { get; set; }
        public virtual ZAKAZ ZAKAZ { get; set; }
    }
    public partial class PURCHASE
    {
        public decimal Sum => (decimal)(quantity * PRODUCTS.price);
    }
}
